### ISSUE TITLE
Please update for Swift 5.5 & SwiftLint 0.45

### ISSUE THREAD

**Issue by StarLard** [norio-nomura/docker-swiftlint#20]
SwiftLint 0.45 contains key fixes for Swift 5.5 Concurrency. Would greatly appreciate an update!

**Comment by Nef10** [comment]
@norio-nomura First of all thanks for providing these images! I noticed you updated the repo this week, however the docker images have not been pushed to Docker Hub, as you removed the hook for this. Any plans to push them? Thanks!

**Comment by norio-nomura** [comment]
The images had not been updated due to the end of Docker Hub autobuild feature for the free plan.
Now, the images has been updated with changes to use GitHub Actions to push the images to Docker Hub.
In addition, the same image is now placed in [GitHub Packages](https://github.com/norio-nomura/docker-swiftlint/pkgs/container/swiftlint).

**Comment by Nef10** [comment]
Thank you!
